trigger:
- none
stages:
- stage: BuildStage
  jobs:
  - job: BuildJob
    pool:
      vmImage: ubuntu-latest
    variables:
      BuildConfiguration: Release
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '-c $(BuildConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-c $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'

- stage: DevStage
  dependsOn: "BuildStage"
  jobs:
  - job: DevJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        downloadPath: '$(System.ArtifactsDirectory)'
        
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'svc'
        appType: 'webAppLinux'
        WebAppName: 'azurewebdev'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
